# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 12:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_auto_20180309_0917'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
